### ISSUE TITLE
OAuth2.0 consumer_key and consumer_secret

### ISSUE THREAD

**Issue by enkemari** [3pillarlabs/socialauth-android#10]
I'm a bit thrown by this. Your "Guide Google" page (found here: https://github.com/3pillarlabs/socialauth-android/wiki/Guide-Google) is out dated in that it probably uses OAuth 1, which has been deprecated. It also has the heading of "Step by Step Guide to Get Twitter consumer key and secrets" while it's for Google :\

Are you able to update this soon?

I'm sifting through the Google API pages and documentation, but various terms are being used for the same things and I'm referred to pages or menu options that don't exist so I'm very confused and am hoping that this is monitored. :\

Kind regards,
E.

**Comment by cn123h** [comment]
thanks @vineetmobile you saved my day!
