### ISSUE TITLE
Integration with Android Studio

### ISSUE THREAD

**Issue by MarmaCinas** [3pillarlabs/socialauth-android#29]

**Comment by pelukron** [comment]
yes, you need add two jars in dir "libs" and compile in gradle like this
dependencies {
    compile files('libs/socialauth-4.4.jar')
    compile files('libs/socialauth-android-3.2.jar')
}

http://stackoverflow.com/questions/16608135/android-studio-add-jar-as-library

**Comment by sayantam** [comment]
New build system compatible with Android Studio released.
