### ISSUE TITLE
Status not updated. Return Status code :403

### ISSUE THREAD

**Issue by joginder89** [3pillarlabs/socialauth-android#59]
Hi I get this Error with Facebook Status update:

org.brickred.socialauth.exception.SocialAuthException: Status not updated. Return Status code :403

Linkedin and Twitter Status update working fine, but I have problem with Facebook and Google+ status update.

Thank you.

**Comment by manawaraquevix** [comment]
I am getting same error with facebook status update. If you resolve this issue, please share here.

**Comment by joginder89** [comment]
You should register your id as developer in facebook application until you submit your application to facebook for review.

**Comment by manawaraquevix** [comment]
Already registered.
