### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by tarcisioreis** [3pillarlabs/socialauth-android#60]
This error giving both your key, as my I registered on linkedin. Error: 

05-18 17:16:05.134 11594-11820/br.exemplosocialoauth D/SocialAuthError﹕ org.brickred.socialauth.exception.SocialAuthConfigurationException: Application keys are not correct. The server running the application should be same that was registered to get the keys.

05-18 17:16:05.135 11594-11820/br.exemplosocialoauth I/Script﹕ URL Authentication error

within the SocialAuthAdapter class has a static function called Provider and have it LINKEDIN ("linkedin", "http://socialauth.in/socialauthdemo/socialAuthSuccessAction.do", "http://socialauth.in/socialauthdemo/socialAuthSuccessAction.do? oauth_problem "),
in which an error occurs.

**Comment by rambabupudari** [comment]
@3pillarlabs  please give the solution or else refer the #ticket number for this issue

**Comment by 3pillarlabs** [comment]
Fixed in SocialAuth version 4.9. Please download jar from Maven and use in
SocialAuth project.

**Comment by rambabupudari** [comment]
thanq @3pillarlabs  working fine now
