### ISSUE TITLE
Authentication Error: URL Authentication error with Linkedin

### ISSUE THREAD

**Issue by joginder89** [3pillarlabs/socialauth-android#61]
When I try to share content on Linkedin I get 
org.brickred.socialauth.exception.SocialAuthConfigurationException: Application keys are not correct. The server running the application should be same that was registered to get the keys.
Although keys are correct. These key are working some days back but now give error. These keys are working with other library.

Full Logcat is 

Selected provider is linkedin
Loading keys and secrets from configuration
Loading application configuration
Starting webview for authentication
Loading plugins
Loading plugin :: org.brickred.socialauth.plugin.linkedin.FeedPluginImpl
Loading plugin :: org.brickred.socialauth.plugin.linkedin.CareerPluginImpl
Determining URL for redirection
org.brickred.socialauth.exception.SocialAuthConfigurationException: Application keys are not correct. The server running the application should be same that was registered to get the keys.

**Comment by 3pillarlabs** [comment]
Yes, we are aware of this issue and working on a fix.

**Comment by tarcisioreis** [comment]
I have same problem.

Esta dando erro tanto com a sua chave, quanto a minha que registrei no linkedin. Erro:

05-18 17:16:05.134 11594-11820/br.exemplosocialoauth D/SocialAuthError﹕ org.brickred.socialauth.exception.SocialAuthConfigurationException: Application keys are not correct. The server running the application should be same that was registered to get the keys.

05-18 17:16:05.135 11594-11820/br.exemplosocialoauth I/Script﹕ URL Authentication error

dentro da classe SocialAuthAdapter tem uma função estatica chamada Provider e tem isso LINKEDIN("linkedin", "http://socialauth.in/socialauthdemo/socialAuthSuccessAction.do", "http://socialauth.in/socialauthdemo/socialAuthSuccessAction.do?oauth_problem"),
no qual ocorre erro.

**Comment by joginder89** [comment]
@tarcisioreis sorry but I do not understand what you want to say please use English language.  If you have solved the problem let me know.

**Comment by tarcisioreis** [comment]
When will this fix?

@joginder89

**Comment by 3pillarlabs** [comment]
Authentication issue fixed, working to deploy to Maven central.

**Comment by joginder89** [comment]
I am using socialauth-4.4.jar and socialauth-android-3.2.jar . How to upgrade these files. I am using Android Studio. Whether I need to add any dependencies inside build.gradle .

**Comment by stefanbaritchii** [comment]
Yes you need to update this in build.gradle:

dependencies {
    compile files('libs/socialauth-x.x.jar')
    compile files('libs/socialauth-android-x.x.jar')
}

where x.x is the version that you want to upgrade to.

**Comment by joginder89** [comment]
@3pillarlabs From where I can get the updated jar files because still I am getting this error. Currently I am using socialauth-4.4.jar and socialauth-android-3.2.jar .

**Comment by 3pillarlabs** [comment]
You can get the jar from Maven directly:
http://search.maven.org/remotecontent?filepath=org/brickred/socialauth/4.9/socialauth-4.9.jar
.

**Comment by joginder89** [comment]
@3pillarlabs Thank you. Now its working.
