### ISSUE TITLE
Why not Windows Live provider?

### ISSUE THREAD

**Issue by SirLouen** [3pillarlabs/socialauth-android#62]
I've seen multiple integrations from various low-key api providers, but not windows live by default. any reasons why I should take care of when trying to implement a custom based on this popular service?

**Comment by abhinav-maheshwari** [comment]
You can use Hotmail provider, it is actually Windows Live api. Please let us know if you face any issues, it has not been updated for quite some time, but we have also not received any issues related to Windows Live. The reasons for naming are historical :)

**Comment by sayantam** [comment]
This has been added in the latest release. It was available in SocialAuth but not SocialAuth Android.
