### ISSUE TITLE
System.out.println calls in the code

### ISSUE THREAD

**Issue by MMahach** [3pillarlabs/socialauth-android#74]
Hello,

I've included your library into my project and noticed, that lines with tag "System.out" have appeared in the log. Are you serious? Possibly user's sensitive info dumping into sys.out?? Well... Excuse me if I'm wrong, but it looks a bit weird, isn't it?

The affected classes are:
- SocialAuthAdapter.java -> private void connectProvider(final Context ctx, final Provider provider);
- SocialAuthDialog.java -> private void writeToken(AuthProvider auth);

Would it be possible to patch these issues soon? Thank you in advance.

**Comment by sayantam** [comment]
You are right, they shouldn't be there. If possible, please send a pull request to fix these.

**Comment by Diwakar1988** [comment]
Removed System.out.println calls from code, we are fixing some more issue, hence these changes will be deployed on jCenter after some time but available on GitHub.
Thanks for pointing!
