### ISSUE TITLE
Linkedin org.brickred.socialauth.android.SocialAuthError: URL Authentication error

### ISSUE THREAD

**Issue by SivaGovindan** [3pillarlabs/socialauth-android#76]
Hi team,

i am faceing this error i am using your example code "Custom-UI".

Kindly fix this

lib:4.9 and 3.2 only used in that example

**Comment by Diwakar1988** [comment]
Hi,

Looks like you are using very old version of socialauth and socialauth-android lib. There are multiple changes in between.

You can follow one of the inline step to resolve your issue:
1. You can use gradle dependency for latest libs i.e. 
   compile 'org.brickred:socialauth:4.12'
   compile 'org.brickred:socialauth-android:3.2.1'
2. You can use our latest gradle based project (Please checkout our latest code from master) 

Please let us know if you are still facing any issue.

Thanks!
