### ISSUE TITLE
Problem in facebook login while authenticate with facebook 

### ISSUE THREAD

**Issue by ShriKush** [3pillarlabs/socialauth-android#78]
Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/Facebook-login/permissions

**Comment by pipiscrew** [comment]
you have to set manual the permissions, just tested 

social_adapter.addConfig(Provider.FACEBOOK, "app_id", "secret", "email");


read more https://developers.facebook.com/docs/facebook-login/permissions

**Comment by pipiscrew** [comment]
http://www.pipiscrew.com/2014/02/socialauth-android/

scroll down

**Comment by pipiscrew** [comment]
@rcristian 
should make it official^

**Comment by sayantam** [comment]
Please upgrade to socialauth 4.11. You can get the jar from Maven or Sourceforge.

**Comment by pipiscrew** [comment]
oh my god, you have to write it to front page at README.md.... users still asking for help every day..

**Comment by sayantam** [comment]
@pipiscrew hey - thanks for your help. We've converted this to a gradle project with socialauth dependency.
