### ISSUE TITLE
Problem in facebook login while authenticate with Social Auth Lib

### ISSUE THREAD

**Issue by ShriKush** [3pillarlabs/socialauth-android#79]
I am trying to integrate facebook login but getting following error 

Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/Facebook-login/permissions

Please help me out.

**Comment by sayantam** [comment]
Please upgrade socialauth jar to 4.11 version. You can download this jar
from Maven or Sourceforge.
