### ISSUE TITLE
Please add gradle support 

### ISSUE THREAD

**Issue by gabin8** [3pillarlabs/socialauth-android#8]
Please add gradle support to project

**Comment by radu-topor** [comment]
I second this! Would be an useful and easy to implement improvement on the SDK's usability.

**Comment by sayantam** [comment]
Done.

**Comment by silviahisham** [comment]
What is the gradle dependency please?

**Comment by sayantam** [comment]
compile 'org.brickred:socialauth-android:3.2.1'

(available from Maven central)
