### ISSUE TITLE
Check if Facebook is logged in?

### ISSUE THREAD

**Issue by IamJackppot** [3pillarlabs/socialauth-android#83]
I can't seem to find any way to check if the user has already logged into Facebook.

Is there any method to check if the user has already logged in?

Thank you for your time.

**Comment by sayantam** [comment]
Does this pertain to storing the state of the login? If so, can you maintain the state in your app once the provider returns the profile?

**Comment by IamJackppot** [comment]
Yes, I think it does. Are there any examples of ways to store the login state?

**Comment by sayantam** [comment]
This code base has 3 examples: custom-ui, share-bar and share-button. I think if you study the code for either share-button or custom-ui, you would probably get an idea of how this can be done in your app.

**Comment by IamJackppot** [comment]
So, what I've got thus far is:

I'm calling the following to initially log into Facebook:

 ```
SOCAUTHAdapter = new SocialAuthAdapter(new ResponseListener());

SOCAUTHAdapter.authorize(getActivity(),
                SocialAuthAdapter.Provider.FACEBOOK);
```

Then, in the response listener when the user is logged in, I am storing the Access Grant key in SharedPreferences.

```
private final class ResponseListener implements DialogListener {

        @Override
        public void onComplete(Bundle values) {

            Log.d("Custom-UI", "Successful");
            
            SOCAUTHAdapter
                    .getAlbumsAsync(new SocialAuthListener<List<Album>>() {

                        @Override
                        public void onExecute(String arg0, final List<Album> t) {
                            // TODO Auto-generated method stub

                            editor.putString("FACEBOOK", SOCAUTHAdapter.getCurrentProvider().getAccessGrant().getKey());
                            editor.apply();
                
                   
                        }

                        @Override
                        public void onError(SocialAuthError arg0) {
                            // TODO Auto-generated method stub

                        }
                    });

        }

        @Override
        public void onError(SocialAuthError error) {
            Log.d("Custom-UI", "Error");
            error.printStackTrace();
        }

        @Override
        public void onCancel() {

        }

        @Override
        public void onBack() {

            custom_progress_wheel.dismiss();


        }

    }
```

Now, I can't find a way I can re-use this access token, so, that when I open up an Activity, I can pass this key to Social Auth and it will see that the user has already logged in, so, I can then access their albums etc without having to call:

        ```
SOCAUTHAdapter.authorize(getActivity(),
                        SocialAuthAdapter.Provider.FACEBOOK);
```

again. I've looked into the source files and can't find a way, would you be able to point at a directory where this is applicable. Thanks again.

**Comment by sayantam** [comment]
Please check this SO question - http://stackoverflow.com/questions/22776780/how-to-get-and-reuse-access-token-in-social-auth-android
