### ISSUE TITLE
Getting more than 25 pictures with Facebook

### ISSUE THREAD

**Issue by IamJackppot** [3pillarlabs/socialauth-android#86]
I am using this library to retrieve albums from the user, and then fetching the album images, and I've realized that you can only fetch 25 images. Is there a way to fetch more? maybe pagination or something. How would I achieve that with this library? is this documented somewhere. 

Thanks in advance for your time.

**Comment by sayantam** [comment]
pagination isn't part if the common API in SocialAuth. Please write a
plugin for this.

-- Sent from my iPhone

On 05-Mar-2016, at 3:53 am, IamJackppot <notifications@github.com> wrote:

I am using this library to retrieve albums from the user, and then fetching
the album images, and I've realized that you can only fetch 25 images. Is
there a way to fetch more? maybe pagination or something. How would I
achieve that with this library? is this documented somewhere.

Thanks in advance for your time.

—
Reply to this email directly or view it on GitHub
<https://github.com/3pillarlabs/socialauth-android/issues/86>.

**Comment by IamJackppot** [comment]
So, isn't there any way to retrieve more than 25 pictures?

**Comment by sayantam** [comment]
If the provider enables pagination, then it can be added as a SocialAuth
plugin -
https://github.com/3pillarlabs/socialauth/wiki/How-To-Write-Custom-Plugin-In-SocialAuth
.

This plugin jar should be present in your classpath along with main
SocialAuth jar.
